### ISSUE TITLE
Some issues I found

### ISSUE THREAD

**Issue by GraeMcDevit** [mlus-asuka/ThirstCanteen#1]
Canteens disappear sometimes when emptied
Sometimes when the canteens are put in a furnace the water is 0/4 rather than 4/4 and when drinking from a canteen with 0/4 water it causes you to lose water.

**Comment by mlus-asuka** [comment]
yep,I already fixed.it won't disappear anymore. And I tried to put it into furnance many times, but nothing went wrong. if there is any problem still in version 1.2, hope you can tell me how to replicate it.
