### ISSUE TITLE
Crash using ThirstCanteen

### ISSUE THREAD

**Issue by SaveTheJohnDoe** [mlus-asuka/ThirstCanteen#5]
[crash-2024-06-23_10.56.41-client.txt](https://github.com/user-attachments/files/15944083/crash-2024-06-23_10.56.41-client.txt)

See attached crash report. Right-clicked canteen onto a Create belt and game crashed ):

Thanks for your work put onto this mod nonetheless! <3

**Comment by mlus-asuka** [comment]
okay, this is actually a bug of thirst. but don't worry i will handle it

**Comment by mlus-asuka** [comment]
Fixed in Thirst 1.3.9
