### ISSUE TITLE
1.18.2 of ThirstCanteen will cause the game to crash.

### ISSUE THREAD

**Issue by Harvey2433** [mlus-asuka/ThirstCanteen#6]
Mod Version:1.5
Thirst Version:1.3.7
If the latest version of the thirst mod is not used, it will cause a crash.

crash-report:
[crash-2024-07-03_13.52.29-fml.txt](https://github.com/user-attachments/files/16077731/crash-2024-07-03_13.52.29-fml.txt)
latest:
[latest.log](https://github.com/user-attachments/files/16077733/latest.log)

**Comment by mlus-asuka** [comment]
you must use Thirst 1.3.8 above if you are using Thirst Canteen 1.4 above. Because I changed Thirst API since 1.3.8

**Comment by Harvey2433** [comment]
OK
