### ISSUE TITLE
The Mekanism mod smelting causes issues with the ThirstCanteen

### ISSUE THREAD

**Issue by Harvey2433** [mlus-asuka/ThirstCanteen#7]
There is an issue when smelting a Dragon Bottle with the Mekanism mod.
Please watch the video
https://github.com/mlus-asuka/ThirstCanteen/assets/109860705/25ed9521-d9ea-4c00-8d01-491779254115

latest:
[latest.log](https://github.com/user-attachments/files/16078235/latest.log)

**Comment by mlus-asuka** [comment]
居然还有高手。昨天看了一下机械动力和农夫乐事的配方写法，针对修了一下。没想到mek还有新的写法

**Comment by Harvey2433** [comment]
下次用中文发issue了
GPT翻译的（
