### ISSUE TITLE
水壶可以附魔经验修补和耐久3

### ISSUE THREAD

**Issue by Harvey2433** [mlus-asuka/ThirstCanteen#8]
用经验可以直接把水壶的耐久度修满
mek熔炼工厂熔炼水壶会导致丢失物品数据

https://github.com/mlus-asuka/ThirstCanteen/assets/109860705/0a22ca56-1440-476f-b5ee-0970a6116095

latest:
[latest.log](https://github.com/user-attachments/files/16078624/latest.log)

**Comment by mlus-asuka** [comment]
修好了。等1.6发布吧

**Comment by Harvey2433** [comment]
ok

**Comment by mlus-asuka** [comment]
Mek的满纯净度停止熔炼写不了，1.21版本之前的都是忽视原料NBT的。但是原版和其他mod写了

**Comment by Harvey2433** [comment]
ok
